//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoTrakMobileService.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPART_ATTACH_FILESTREAM
    {
        public System.Guid guid { get; set; }
        public long compart_attach_auto { get; set; }
        public Nullable<long> compartid_auto { get; set; }
        public Nullable<long> comparttype_auto { get; set; }
        public Nullable<int> tool_auto { get; set; }
        public Nullable<int> compart_attach_type_auto { get; set; }
        public Nullable<long> user_auto { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public string comment { get; set; }
        public string attachment_name { get; set; }
        public byte[] attachment { get; set; }
        public Nullable<int> inspection_auto { get; set; }
        public Nullable<int> position { get; set; }
    
        public virtual COMPART_ATTACH_TYPE COMPART_ATTACH_TYPE { get; set; }
    }
}
