//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoTrakMobileService.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        public CUSTOMER()
        {
            this.CRSFs = new HashSet<CRSF>();
            this.LU_IMPLEMENT = new HashSet<LU_IMPLEMENT>();
        }
    
        public long customer_auto { get; set; }
        public string custid { get; set; }
        public string cust_name { get; set; }
        public string cust_street { get; set; }
        public string cust_suburb { get; set; }
        public string cust_postcode { get; set; }
        public string cust_state { get; set; }
        public string cust_country { get; set; }
        public string cust_phone { get; set; }
        public string cust_mobile { get; set; }
        public string cust_fax { get; set; }
        public string cust_email { get; set; }
        public string note { get; set; }
        public Nullable<long> customer_auto_main { get; set; }
        public string companyname { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_user { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_user { get; set; }
        public string cust_formid { get; set; }
        public string db_custid { get; set; }
        public string cust_street2 { get; set; }
        public bool active { get; set; }
        public string cust_billing_street { get; set; }
        public string cust_billing_street2 { get; set; }
        public string cust_billing_suburb { get; set; }
        public string cust_billing_postcode { get; set; }
        public string cust_billing_state { get; set; }
        public string cust_billing_country { get; set; }
        public bool billing_address { get; set; }
        public Nullable<byte> primary_language { get; set; }
        public Nullable<byte> second_language { get; set; }
        public Nullable<bool> is_account_payment { get; set; }
        public Nullable<long> cs_customer_auto { get; set; }
        public Nullable<bool> labonly { get; set; }
        public Nullable<int> cust_country_auto { get; set; }
        public Nullable<int> cust_billing_country_auto { get; set; }
        public Nullable<int> payment_terms { get; set; }
        public string logo_name { get; set; }
        public Nullable<byte> district_auto { get; set; }
        public Nullable<long> cs_ws_url_auto { get; set; }
        public string business_system { get; set; }
        public Nullable<bool> ic_workorder { get; set; }
        public Nullable<bool> ic_component_forecast { get; set; }
        public string business_system_key { get; set; }
        public Nullable<decimal> quote_discount { get; set; }
        public Nullable<long> ProfileID { get; set; }
        public bool Showlimits { get; set; }
        public Nullable<bool> send_fax { get; set; }
        public Nullable<bool> send_email { get; set; }
        public Nullable<bool> send_hardcopy { get; set; }
        public string Payment_Type { get; set; }
        public string Contact_Type { get; set; }
        public Nullable<decimal> terms_Exceeded { get; set; }
        public Nullable<long> AS400_CUSTOMER_AUTO { get; set; }
        public string invoice_note { get; set; }
        public byte[] logo { get; set; }
        public int DealershipId { get; set; }
        public Nullable<long> CreatedByUserId { get; set; }
        public Nullable<int> subPremise { get; set; }
        public string fullAddress { get; set; }
        public Nullable<int> SelectedReportId { get; set; }
    
        public virtual ICollection<CRSF> CRSFs { get; set; }
        public virtual ICollection<LU_IMPLEMENT> LU_IMPLEMENT { get; set; }
    }
}
