//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoTrakMobileService.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GET_IMPLEMENT_MAKE_MODEL
    {
        public long implement_make_model_auto { get; set; }
        public long implement_auto { get; set; }
        public Nullable<long> make_auto { get; set; }
        public long model_auto { get; set; }
    }
}
