//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoTrakMobileService.DataAccess.Model
{
    using System;
    
    public partial class LimitsForEquipmentResult
    {
        public string models { get; set; }
        public int compartid_auto { get; set; }
        public string makedesc { get; set; }
        public string comparttype { get; set; }
        public string compart { get; set; }
        public string compartid { get; set; }
        public string method { get; set; }
        public string itm_tool { get; set; }
        public Nullable<decimal> start_depth_new { get; set; }
        public Nullable<decimal> wear_depth_10_percent { get; set; }
        public Nullable<decimal> wear_depth_20_percent { get; set; }
        public Nullable<decimal> wear_depth_30_percent { get; set; }
        public Nullable<decimal> wear_depth_40_percent { get; set; }
        public Nullable<decimal> wear_depth_50_percent { get; set; }
        public Nullable<decimal> wear_depth_60_percent { get; set; }
        public Nullable<decimal> wear_depth_70_percent { get; set; }
        public Nullable<decimal> wear_depth_80_percent { get; set; }
        public Nullable<decimal> wear_depth_90_percent { get; set; }
        public Nullable<decimal> wear_depth_100_percent { get; set; }
        public Nullable<decimal> wear_depth_110_percent { get; set; }
        public Nullable<decimal> wear_depth_120_percent { get; set; }
        public string cat_tool { get; set; }
        public Nullable<decimal> hi_inflectionPoint { get; set; }
        public Nullable<decimal> hi_slope1 { get; set; }
        public Nullable<decimal> hi_intercept1 { get; set; }
        public Nullable<decimal> hi_slope2 { get; set; }
        public Nullable<decimal> hi_intercept2 { get; set; }
        public Nullable<decimal> mi_inflectionPoint { get; set; }
        public Nullable<decimal> mi_slope1 { get; set; }
        public Nullable<decimal> mi_intercept1 { get; set; }
        public Nullable<decimal> mi_slope2 { get; set; }
        public Nullable<decimal> mi_intercept2 { get; set; }
        public Nullable<int> slope { get; set; }
        public Nullable<decimal> adjust_base { get; set; }
        public string komatsu_tool { get; set; }
        public Nullable<decimal> impact_slope { get; set; }
        public Nullable<decimal> normal_slope { get; set; }
        public Nullable<decimal> impact_intercept { get; set; }
        public Nullable<decimal> normal_intercept { get; set; }
        public string Hitachi_tool { get; set; }
        public Nullable<decimal> hit_impact_slope { get; set; }
        public Nullable<decimal> hit_normal_slope { get; set; }
        public Nullable<decimal> hit_impact_intercept { get; set; }
        public Nullable<decimal> hit_normal_intercept { get; set; }
        public string Liebherr_tool { get; set; }
        public Nullable<decimal> lie_impact_slope { get; set; }
        public Nullable<decimal> lie_normal_slope { get; set; }
        public Nullable<decimal> lie_impact_intercept { get; set; }
        public Nullable<decimal> lie_normal_intercept { get; set; }
    }
}
