//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoTrakMobileService.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LINK_LOCATION
    {
        public long location_auto { get; set; }
        public long equipmentid_auto { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<decimal> latitude { get; set; }
        public Nullable<decimal> longitude { get; set; }
        public Nullable<long> messageId { get; set; }
        public Nullable<long> masterMsgId { get; set; }
        public Nullable<System.DateTime> receivedTime { get; set; }
        public Nullable<System.DateTime> date_import { get; set; }
    
        public virtual EQUIPMENT EQUIPMENT { get; set; }
    }
}
