//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoTrakMobileService.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LU_COMPART
    {
        public LU_COMPART()
        {
            this.GENERAL_EQ_UNIT = new HashSet<GENERAL_EQ_UNIT>();
            this.TRACK_COMPART_EXT = new HashSet<TRACK_COMPART_EXT>();
        }
    
        public int compartid_auto { get; set; }
        public string compartid { get; set; }
        public string compart { get; set; }
        public Nullable<int> hrs { get; set; }
        public byte progid { get; set; }
        public Nullable<bool> Left { get; set; }
        public Nullable<int> parentid_auto { get; set; }
        public string parentid { get; set; }
        public Nullable<short> childoptid { get; set; }
        public Nullable<bool> multiple { get; set; }
        public Nullable<int> fixedamount { get; set; }
        public Nullable<long> implement_auto { get; set; }
        public Nullable<bool> core { get; set; }
        public string group_id { get; set; }
        public Nullable<decimal> expected_life { get; set; }
        public Nullable<decimal> expected_cost { get; set; }
        public int comparttype_auto { get; set; }
        public string companyname { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_user { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_user { get; set; }
        public Nullable<short> bowldisplayorder { get; set; }
        public Nullable<short> track_comp_row { get; set; }
        public string track_comp_cts_maintype { get; set; }
        public string track_comp_cts_subtype { get; set; }
        public Nullable<int> smcs_code { get; set; }
        public string modifier_code { get; set; }
        public short sumpcapacity { get; set; }
        public short max_rebuilt { get; set; }
        public short oilsample_interval { get; set; }
        public short oilchg_interval { get; set; }
        public Nullable<bool> insp_item { get; set; }
        public Nullable<short> insp_interval { get; set; }
        public Nullable<short> insp_uom { get; set; }
        public string compart_note { get; set; }
        public Nullable<int> sorder { get; set; }
        public string hydraulic_inspect_symptoms { get; set; }
        public Nullable<int> cs_compart_auto { get; set; }
        public Nullable<int> positionid_auto { get; set; }
        public Nullable<bool> allow_duplicate { get; set; }
        public Nullable<long> standard_compartid_auto { get; set; }
        public Nullable<int> ranking_auto { get; set; }
    
        public virtual ICollection<GENERAL_EQ_UNIT> GENERAL_EQ_UNIT { get; set; }
        public virtual LU_COMPART_TYPE LU_COMPART_TYPE { get; set; }
        public virtual ICollection<TRACK_COMPART_EXT> TRACK_COMPART_EXT { get; set; }
    }
}
