//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoTrakMobileService.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LU_MMTA
    {
        public LU_MMTA()
        {
            this.EQUIPMENTs = new HashSet<EQUIPMENT>();
        }
    
        public int mmtaid_auto { get; set; }
        public int make_auto { get; set; }
        public int model_auto { get; set; }
        public int type_auto { get; set; }
        public Nullable<int> arrangement_auto { get; set; }
        public Nullable<short> app_auto { get; set; }
        public Nullable<int> service_cycle_type_auto { get; set; }
        public System.DateTime expiry_date { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_user { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_user { get; set; }
        public Nullable<int> cs_mmtaid_auto { get; set; }
    
        public virtual ICollection<EQUIPMENT> EQUIPMENTs { get; set; }
        public virtual MODEL MODEL { get; set; }
        public virtual TYPE TYPE { get; set; }
        public virtual MAKE MAKE { get; set; }
    }
}
