//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoTrakMobileService.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LU_Module_Sub
    {
        public long Module_sub_auto { get; set; }
        public string Serialno { get; set; }
        public Nullable<int> Module_progid { get; set; }
        public Nullable<long> SMU { get; set; }
        public Nullable<long> CMU { get; set; }
        public Nullable<long> SMU_at_install { get; set; }
        public Nullable<long> LTD_at_install { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
        public Nullable<long> LTD { get; set; }
        public Nullable<long> equipmentid_auto { get; set; }
        public Nullable<long> crsf_auto { get; set; }
        public Nullable<int> make_auto { get; set; }
        public Nullable<int> model_auto { get; set; }
        public Nullable<long> type_auto { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public Nullable<int> modifiedBy { get; set; }
        public string reason { get; set; }
        public string notes { get; set; }
        public Nullable<long> system_LTD_on_removal { get; set; }
        public Nullable<long> equipment_LTD_at_attachment { get; set; }
        public Nullable<int> installation_status { get; set; }
        public int systemTypeEnumIndex { get; set; }
    
        public virtual EQUIPMENT EQUIPMENT { get; set; }
    }
}
