//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoTrakMobileService.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LU_SYSTEM
    {
        public LU_SYSTEM()
        {
            this.LU_COMPART_TYPE = new HashSet<LU_COMPART_TYPE>();
        }
    
        public short system_auto { get; set; }
        public string system_desc { get; set; }
        public Nullable<int> cs_system_auto { get; set; }
        public Nullable<byte> progid { get; set; }
        public Nullable<long> standard_system_auto { get; set; }
        public Nullable<long> ranking_auto { get; set; }
        public Nullable<int> sorder { get; set; }
        public Nullable<int> SMCSCODE { get; set; }
    
        public virtual ICollection<LU_COMPART_TYPE> LU_COMPART_TYPE { get; set; }
    }
}
