//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoTrakMobileService.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mbl_NewEquipment
    {
        public long equipmentid_auto { get; set; }
        public string serialno { get; set; }
        public string unitno { get; set; }
        public string description { get; set; }
        public Nullable<long> derived_from { get; set; }
        public int mmtaid_auto { get; set; }
        public Nullable<byte> market_auto { get; set; }
        public Nullable<byte> measure_unit { get; set; }
        public Nullable<int> op_hrs_per_day { get; set; }
        public Nullable<byte> op_dist_uom { get; set; }
        public string op_range { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<long> smu_at_start { get; set; }
        public Nullable<long> distance_at_start { get; set; }
        public Nullable<long> smu_at_end { get; set; }
        public Nullable<long> distance_at_end { get; set; }
        public Nullable<long> currentsmu { get; set; }
        public Nullable<long> currentdistance { get; set; }
        public Nullable<System.DateTime> last_reading_date { get; set; }
        public string notes { get; set; }
        public Nullable<long> LTD_at_start { get; set; }
        public long crsf_auto { get; set; }
        public string location { get; set; }
        public Nullable<int> purchase_op_hrs { get; set; }
        public Nullable<int> purchase_op_dist { get; set; }
        public Nullable<System.DateTime> purchase_date { get; set; }
        public Nullable<decimal> purchase_cost { get; set; }
        public Nullable<int> deprate { get; set; }
        public string depmethod { get; set; }
        public string uccode { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_user { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_user { get; set; }
        public int equip_status { get; set; }
        public string regno { get; set; }
        public Nullable<short> errorcode { get; set; }
        public Nullable<long> fleet_auto { get; set; }
        public Nullable<bool> update_accept { get; set; }
        public string DBS_serialno { get; set; }
        public Nullable<bool> da_inclusion { get; set; }
        public Nullable<short> status_auto { get; set; }
        public Nullable<System.DateTime> first_reg_start_date { get; set; }
        public Nullable<System.DateTime> reg_start_date { get; set; }
        public Nullable<short> period_auto { get; set; }
        public Nullable<System.DateTime> reg_expiry_date { get; set; }
        public Nullable<int> service_cycle_type_auto { get; set; }
        public Nullable<int> turbo_mod_auto { get; set; }
        public Nullable<int> control_sys_auto { get; set; }
        public Nullable<int> calendar_period { get; set; }
        public Nullable<byte> recurring_int_auto { get; set; }
        public Nullable<System.DateTime> no_contract_fcast_date_at_start { get; set; }
        public Nullable<int> no_contract_fcast_s_cycle_auto_at_end { get; set; }
        public Nullable<int> no_contract_fcast_s_cycle_auto_at_start { get; set; }
        public Nullable<long> no_contract_fcast_smu_at_start { get; set; }
        public Nullable<int> track_make_auto { get; set; }
        public Nullable<long> track_code_auto { get; set; }
        public Nullable<long> cs_equip_auto { get; set; }
        public Nullable<long> dtd_at_start { get; set; }
        public Nullable<long> no_contract_fcast_smu_at_end { get; set; }
        public Nullable<long> no_contract_fcast_LTD_at_start { get; set; }
        public Nullable<long> no_contract_fcast_LTD_at_end { get; set; }
        public Nullable<System.DateTime> no_contract_fcast_date_at_end { get; set; }
        public Nullable<byte> ranking_auto { get; set; }
        public Nullable<bool> secondary_uom_isHours { get; set; }
        public Nullable<bool> secondary_uom_isDistance { get; set; }
        public Nullable<bool> secondary_uom_isKWHours { get; set; }
        public Nullable<bool> secondary_uom_isCalendar { get; set; }
        public Nullable<bool> secondary_uom_isFuelBurn { get; set; }
        public Nullable<decimal> smu_sec_reading { get; set; }
        public Nullable<decimal> smu_ltd_sec_reading { get; set; }
        public Nullable<decimal> distance_sec_reading { get; set; }
        public Nullable<decimal> distance_ltd_sec_reading { get; set; }
        public Nullable<byte> distance_sec_reading_uom { get; set; }
        public Nullable<decimal> kw_hrs_sec_reading { get; set; }
        public Nullable<decimal> kw_hrs_ltd_sec_reading { get; set; }
        public Nullable<decimal> fuel_burn_sec_reading { get; set; }
        public Nullable<decimal> fuel_burn_ltd_sec_reading { get; set; }
        public Nullable<decimal> calender_sec_reading { get; set; }
        public Nullable<byte> calender_sec_reading_uom { get; set; }
        public Nullable<decimal> current_smu_sec_reading { get; set; }
        public Nullable<decimal> current_distance_sec_reading { get; set; }
        public Nullable<decimal> current_kw_hrs_sec_reading { get; set; }
        public Nullable<decimal> current_fuel_burn_sec_reading { get; set; }
        public Nullable<decimal> current_calender_sec_reading { get; set; }
        public Nullable<int> health_review_auto { get; set; }
        public Nullable<long> AS400_EQUIPMENT_AUTO { get; set; }
        public Nullable<decimal> Sec_AVGDB_Hours { get; set; }
        public Nullable<decimal> Sec_AVGDB_Distance { get; set; }
        public Nullable<decimal> Sec_AVGDB_KWHOURS { get; set; }
        public Nullable<decimal> Sec_AVGDB_FuelBurn { get; set; }
        public Nullable<decimal> Sec_AVGDB_Calender { get; set; }
        public Nullable<long> no_fcast_Sec_Smu { get; set; }
        public Nullable<long> no_fcast_Sec_distance { get; set; }
        public Nullable<long> no_fcast_Sec_SMU_ltd { get; set; }
        public Nullable<long> no_fcast_Sec_distance_ltd { get; set; }
        public bool vision_link_exist { get; set; }
        public Nullable<System.DateTime> vision_link_import_date { get; set; }
        public string customer_name { get; set; }
        public string jobsite_name { get; set; }
        public string model { get; set; }
        public Nullable<long> pc_equipmentid_auto { get; set; }
        public Nullable<int> pc_inspection_auto { get; set; }
    }
}
