//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoTrakMobileService.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mbl_Track_Inspection
    {
        public int inspection_auto { get; set; }
        public long equipmentid_auto { get; set; }
        public string examiner { get; set; }
        public System.DateTime inspection_date { get; set; }
        public Nullable<int> smu { get; set; }
        public string notes { get; set; }
        public Nullable<decimal> track_sag_left { get; set; }
        public Nullable<decimal> track_sag_right { get; set; }
        public string track_sag_left_status { get; set; }
        public string track_sag_right_status { get; set; }
        public Nullable<decimal> dry_joints_left { get; set; }
        public Nullable<decimal> dry_joints_right { get; set; }
        public Nullable<decimal> ext_cannon_left { get; set; }
        public Nullable<decimal> ext_cannon_right { get; set; }
        public Nullable<decimal> frame_ext_left { get; set; }
        public Nullable<decimal> frame_ext_right { get; set; }
        public string sprocket_left_status { get; set; }
        public string sprocket_right_status { get; set; }
        public Nullable<short> impact { get; set; }
        public Nullable<short> abrasive { get; set; }
        public Nullable<short> moisture { get; set; }
        public Nullable<short> packing { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_user { get; set; }
        public Nullable<System.DateTime> confirmed_date { get; set; }
        public string confirmed_user { get; set; }
        public string evalcode { get; set; }
        public Nullable<short> allowableWear { get; set; }
        public string uccode { get; set; }
        public string uccodedesc { get; set; }
        public Nullable<System.DateTime> last_interp_date { get; set; }
        public string last_interp_user { get; set; }
        public string eval_comment { get; set; }
        public string location { get; set; }
        public string docket_no { get; set; }
        public string ucbrand { get; set; }
        public Nullable<byte> wear { get; set; }
        public Nullable<int> ltd { get; set; }
        public string Jobsite_Comms { get; set; }
        public Nullable<System.DateTime> released_date { get; set; }
        public string released_by { get; set; }
        public string inspection_comments { get; set; }
        public Nullable<int> quote_auto { get; set; }
    }
}
