//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoTrakMobileService.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODEL
    {
        public MODEL()
        {
            this.LU_MMTA = new HashSet<LU_MMTA>();
        }
    
        public int model_auto { get; set; }
        public string modelid { get; set; }
        public string modeldesc { get; set; }
        public System.DateTime created_date { get; set; }
        public string created_user { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_user { get; set; }
        public Nullable<int> track_sag_maximum { get; set; }
        public Nullable<int> track_sag_minimum { get; set; }
        public Nullable<byte> tt_prog_auto { get; set; }
        public Nullable<byte> gb_prog_auto { get; set; }
        public Nullable<byte> axle_no { get; set; }
        public Nullable<bool> isPSC { get; set; }
        public Nullable<short> model_size_auto { get; set; }
        public Nullable<int> cs_model_auto { get; set; }
        public Nullable<bool> cat { get; set; }
        public Nullable<short> model_pricing_level_auto { get; set; }
        public Nullable<short> equip_reg_industry_auto { get; set; }
        public string ModelNote { get; set; }
        public Nullable<decimal> UCSystemCost { get; set; }
        public byte[] ModelImage { get; set; }
        public int LinksInChain { get; set; }
    
        public virtual ICollection<LU_MMTA> LU_MMTA { get; set; }
    }
}
