//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoTrakMobileService.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRACK_DEALERSHIP_LIMITS
    {
        public long dealership_limit_auto { get; set; }
        public Nullable<int> a_limit { get; set; }
        public Nullable<int> b_limit { get; set; }
        public Nullable<int> c_limit { get; set; }
        public Nullable<int> compartid_auto { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_user { get; set; }
    }
}
