//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoTrakMobileService.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRACK_COMPART_EXT
    {
        public long track_compart_ext_auto { get; set; }
        public int compartid_auto { get; set; }
        public Nullable<int> make_auto { get; set; }
        public Nullable<int> tools_auto { get; set; }
        public Nullable<int> budget_life { get; set; }
        public Nullable<int> track_compart_worn_calc_method_auto { get; set; }
    
        public virtual LU_COMPART LU_COMPART { get; set; }
        public virtual TRACK_TOOL TRACK_TOOL { get; set; }
        public virtual TRACK_COMPART_WORN_CALC_METHOD TRACK_COMPART_WORN_CALC_METHOD { get; set; }
        public virtual MAKE MAKE { get; set; }
    }
}
