//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoTrakMobileService.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPE
    {
        public TYPE()
        {
            this.LU_MMTA = new HashSet<LU_MMTA>();
        }
    
        public int type_auto { get; set; }
        public string typeid { get; set; }
        public string typedesc { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_user { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_user { get; set; }
        public Nullable<int> cs_type_auto { get; set; }
        public Nullable<int> blob_auto { get; set; }
        public Nullable<int> blob_large_auto { get; set; }
        public Nullable<long> default_smu { get; set; }
    
        public virtual ICollection<LU_MMTA> LU_MMTA { get; set; }
    }
}
