//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoTrakMobileService.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_TABLE
    {
        public USER_TABLE()
        {
            this.CRSFs = new HashSet<CRSF>();
        }
    
        public long user_auto { get; set; }
        public string userid { get; set; }
        public string username { get; set; }
        public string passwd { get; set; }
        public bool internalemp { get; set; }
        public string email { get; set; }
        public string phone_area_code { get; set; }
        public string phone_number { get; set; }
        public string fax_area_code { get; set; }
        public string fax_number { get; set; }
        public string mobile { get; set; }
        public string street1 { get; set; }
        public string street2 { get; set; }
        public string suburb { get; set; }
        public string postcode { get; set; }
        public string state { get; set; }
        public string country { get; set; }
        public Nullable<int> position_auto { get; set; }
        public byte language_auto { get; set; }
        public string temperature_unit { get; set; }
        public int currency_auto { get; set; }
        public string weight_unit { get; set; }
        public string length_unit { get; set; }
        public string area_unit { get; set; }
        public string volume_unit { get; set; }
        public string pressure_unit { get; set; }
        public bool interpreter { get; set; }
        public bool viewr { get; set; }
        public bool viewe { get; set; }
        public bool active { get; set; }
        public bool first_login { get; set; }
        public Nullable<System.DateTime> last_login_date { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_user { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_user { get; set; }
        public Nullable<bool> rpt_print { get; set; }
        public Nullable<bool> EvalA { get; set; }
        public Nullable<bool> EvalB { get; set; }
        public Nullable<bool> EvalC { get; set; }
        public Nullable<bool> EvalX { get; set; }
        public Nullable<bool> SMS { get; set; }
        public bool @protected { get; set; }
        public string company { get; set; }
        public Nullable<byte> login_moduleid { get; set; }
        public Nullable<short> colorscheme_auto { get; set; }
        public Nullable<System.DateTime> away_start_date { get; set; }
        public Nullable<System.DateTime> away_end_date { get; set; }
        public Nullable<bool> send_fax { get; set; }
        public Nullable<bool> send_email { get; set; }
        public Nullable<bool> send_hardcopy { get; set; }
        public bool attach { get; set; }
        public byte print_copies { get; set; }
        public Nullable<long> customer_auto { get; set; }
        public Nullable<byte> url_auto { get; set; }
        public bool sos { get; set; }
        public Nullable<byte> laboratory_auto { get; set; }
        public Nullable<bool> must_change_password { get; set; }
        public Nullable<byte> invalid_login_count { get; set; }
        public Nullable<System.DateTime> invalid_login_start_time { get; set; }
        public Nullable<System.DateTime> last_password_change { get; set; }
        public Nullable<bool> password_encrypted { get; set; }
        public Nullable<long> CS_UserAuto { get; set; }
        public Nullable<bool> can_create_cs_account { get; set; }
        public Nullable<bool> internalother { get; set; }
        public Nullable<byte> detail_email { get; set; }
        public Nullable<byte> summary_email { get; set; }
        public Nullable<byte> summary_group { get; set; }
        public string comment { get; set; }
        public Nullable<int> country_auto { get; set; }
        public bool suspended { get; set; }
        public Nullable<bool> branded_admin { get; set; }
        public bool IsEquipmentEdit { get; set; }
        public string mob_license { get; set; }
        public string mob_device_id { get; set; }
        public string track_uom { get; set; }
        public Nullable<bool> eq_health { get; set; }
        public Nullable<long> AS400_PSSR_AUTO { get; set; }
        public string AS400_PSSR_EMPNO { get; set; }
        public string cat_id { get; set; }
        public string cat_password { get; set; }
        public Nullable<bool> eq_undercarriage { get; set; }
        public string Position_name_Quote { get; set; }
        public string AspNetUserId { get; set; }
        public Nullable<int> ApplicationAccess { get; set; }
    
        public virtual ICollection<CRSF> CRSFs { get; set; }
    }
}
